### ISSUE TITLE
SSH via remote linux machine

### ISSUE THREAD

**Issue by jlamb85** [fcaviggia/hardening-script-el6#49]
I have the user in the sshusers and wheel group and as soon as I login the system from a remote machine it disconnects me.  Any Ideas??

**Comment by fcaviggia** [comment]
Any issue in the logs (/var/log/messages or /var/log/secure)? Could also be the MACs set in SSH (they are set to FIPS 140-2 defaults)

**Comment by jlamb85** [comment]
I think it is the MACs.  How do I login with ssh if it is FIPS 140-2 ?

**Comment by fcaviggia** [comment]
What client and verison are you using to ssh into the machine? I've seen some issues with .62 putty.

**Comment by jlamb85** [comment]
This is not putty.  This is openssh-5.3p1-104.el6_6.1.x86_64

**Comment by fcaviggia** [comment]
I know there is a way to force the MAC and encryption methods - I'll give this a try here when I get home from a customer's site.

**Comment by jlamb85** [comment]
I can't find anything that allows you to login with a MAC or encryption method at the command line.

**Comment by fcaviggia** [comment]
You can force encryption types on the Linux ssh client. For MACs, change it on the server side under /etc/ssh/sshd_config and restart the sshd service.

**Comment by jacolley** [comment]
To illuminate some things, on the sshd server your trying to connect to, say its 192.168.1.1, 
open a terminal window on that system and issue the following command 
"ssh -vvvv <username>@192.168.1.1"  

If there is a user account problem, you should get the same results as previously seeing from the remote machine. The -vvv will give you some verbose output that could help you locate the root cause.

If your still having problems, from a term windows, stop sshd and start from the command like so: "/sbin/sshd -dddd" and on another terminal window issues  "ssh -vvvv <username>@192.168.1.1"

Another thing to try, maybe first, is " chage <username>" and verify the account is indeed active. I've run into this before and the account will be expired. 

(/var/log/messages or /var/log/secure) as mentioned earlier will also help find these problems too .
open a few more terminal windows and one one issue: "tail -fn  /var/log/secure" on the other issue: "/var/log/messages" 

Let use know what you find.
Jc

**Comment by jlamb85** [comment]
I found out if I use "ssh -c aes256-ctr x.x.x.x" it works
